<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\EventAssos.Domain\EventAssos.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="DTOs\Response\" />
      <Folder Include="Interfaces\Repositories\" />
      <Folder Include="Interfaces\Services\" />
      <Folder Include="Mappers\" />
      <Folder Include="Services\Datas\Tools\" />
    </ItemGroup>

</Project>
