// <auto-generated />
using System;
using EventAssos.Infrastructure.DataBase.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventAssos.Infrastructure.Migrations
{
    [DbContext(typeof(EventAssosDbContext))]
    [Migration("20260320114537_ChangePasswordDupont")]
    partial class ChangePasswordDupont
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CategorieEvenement", b =>
                {
                    b.Property<int>("CategoriesId")
                        .HasColumnType("int");

                    b.Property<Guid>("EvenementsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CategoriesId", "EvenementsId");

                    b.HasIndex("EvenementsId");

                    b.ToTable("EvenementCategories", (string)null);
                });

            modelBuilder.Entity("EventAssos.Domain.Entities.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nom = "Concert"
                        },
                        new
                        {
                            Id = 2,
                            Nom = "Conférence"
                        },
                        new
                        {
                            Id = 3,
                            Nom = "Atelier"
                        },
                        new
                        {
                            Id = 4,
                            Nom = "Autres"
                        });
                });

            modelBuilder.Entity("EventAssos.Domain.Entities.Evenement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateDeCreation")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<DateTime>("DateDebut")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateFin")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateLimiteInscription")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DateMaj")
                        .HasColumnType("datetime");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("Lieu")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<bool>("ListeAttenteActive")
                        .HasColumnType("bit");

                    b.Property<int>("NbMax")
                        .HasColumnType("int");

                    b.Property<int>("NbMin")
                        .HasColumnType("int");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("StatutEvenement")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Evenements");
                });

            modelBuilder.Entity("EventAssos.Domain.Entities.Inscription", b =>
                {
                    b.Property<Guid>("MembreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EvenementId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("EstEnAttente")
                        .HasColumnType("bit");

                    b.Property<DateTime>("InscriptionDate")
                        .HasColumnType("datetime2");

                    b.HasKey("MembreId", "EvenementId");

                    b.HasIndex("EvenementId");

                    b.ToTable("Inscriptions");
                });

            modelBuilder.Entity("EventAssos.Domain.Entities.Membre", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("nvarchar(35)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Pseudo")
                        .IsUnique();

                    b.ToTable("Membres");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            DateNaissance = new DateTime(1978, 8, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "admin@eventassos.com",
                            Genre = 0,
                            Password = "$2a$11$0n/bZzK2T6K.wXyA3YtM.OR8.6.T.wXyA3YtM.OR8.6.T.wXyA3YtM.O",
                            Pseudo = "MmeDupont",
                            Role = 1
                        });
                });

            modelBuilder.Entity("CategorieEvenement", b =>
                {
                    b.HasOne("EventAssos.Domain.Entities.Categorie", null)
                        .WithMany()
                        .HasForeignKey("CategoriesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventAssos.Domain.Entities.Evenement", null)
                        .WithMany()
                        .HasForeignKey("EvenementsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EventAssos.Domain.Entities.Inscription", b =>
                {
                    b.HasOne("EventAssos.Domain.Entities.Evenement", "Evenement")
                        .WithMany("Inscriptions")
                        .HasForeignKey("EvenementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EventAssos.Domain.Entities.Membre", "Membre")
                        .WithMany("Inscriptions")
                        .HasForeignKey("MembreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Evenement");

                    b.Navigation("Membre");
                });

            modelBuilder.Entity("EventAssos.Domain.Entities.Evenement", b =>
                {
                    b.Navigation("Inscriptions");
                });

            modelBuilder.Entity("EventAssos.Domain.Entities.Membre", b =>
                {
                    b.Navigation("Inscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
